export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";

export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const REQUEST_POSTS = "REQUEST_POSTS";


export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";

export const UPVOTE_POST = "UPVOTE_POST";
export const DOWNVOTE_POST = "DOWNVOTE_POST";
export const UPVOTE_COMMENT = "UPVOTE_COMMENT";
export const DOWNVOTE_COMMENT = "DOWNVOTE_COMMENT";

export const SORT_POSTS = "SORT_POSTS";

export const DELETE_REQUEST_POST = "DELETE_REQUEST_POST";
export const DELETE_POST = "DELETE_POST";
export const DELETE_REQUEST_COMMENT = "DELETE_REQUEST_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

export const CREATE_REQUEST_POST = "CREATE_REQUEST_POST";
export const CREATE_POST = "CREATE_POST";
export const CREATE_REQUEST_COMMENT = "CREATE_REQUEST_COMMENT";
export const CREATE_COMMENT = "CREATE_COMMENT";

export const EDIT_REQUEST_POST = "EDIT_REQUEST_POST";
export const EDIT_POST = "EDIT_POST";
export const EDIT_REQUEST_COMMENT = "EDIT_REQUEST_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";