export const ADD_EXAMPLE = 'ADD_EXAMPLE'
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const REQUEST_CATEGORIES = "REQUEST_CATEGORIES";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const REQUEST_POSTS = "REQUEST_POSTS";